name: Node CI

on:
  push:
    branches: 
      - master
      - feature/**
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.11.3
      uses: actions/setup-node@v1
      with:
        node-version: 8.11.3
        registry-url: https://registry.npmjs.org/
    - name: npm install
      run: npm i
    - name: npm test
      run: npm t
      env:
        STRUCTURIZR_WORKSPACE_ID: ${{secrets.STRUCTURIZR_WORKSPACE_ID}}
        STRUCTURIZR_API_KEY: ${{secrets.STRUCTURIZR_API_KEY}}
        STRUCTURIZR_API_SECRET: ${{secrets.STRUCTURIZR_API_SECRET}}
  publish:
    needs: [test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: npm build
      run: npm run build
    - name: publish to npmjs
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
